//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppRegistration
    {
        public int Id { get; set; }
        public string AppName { get; set; }
        public string Url { get; set; }
        public string ImagePath { get; set; }
        public Nullable<short> DefaultAuthorized { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<int> AppType { get; set; }
    
        public virtual AppType AppType1 { get; set; }
    }
}
