//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserValidation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> AppId { get; set; }
        public Nullable<byte> IsAppAdmin { get; set; }
        public Nullable<byte> IsGlobalAdmin { get; set; }
        public Nullable<byte> IsAllowAccess { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    }
}
