//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthModule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class app_authentication_devEntities : DbContext
    {
        public app_authentication_devEntities()
            : base("name=app_authentication_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppRegistration> AppRegistrations { get; set; }
        public virtual DbSet<Authentication> Authentications { get; set; }
        public virtual DbSet<AppUserValidation> AppUserValidations { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AppType> AppTypes { get; set; }
        public virtual DbSet<UserDeviceRegistration> UserDeviceRegistrations { get; set; }
        public virtual DbSet<EConfirmation> EConfirmations { get; set; }
        public virtual DbSet<vw_tblProducts> vw_tblProducts { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<vw_tblCategory> vw_tblCategory { get; set; }
    
        public virtual int sp_I_tblProducts(Nullable<int> prdId, string prdCode, string prdDesc, Nullable<decimal> prdPrice, Nullable<int> active, string cMBy, Nullable<System.DateTime> cMDate, Nullable<int> delete, Nullable<int> catId)
        {
            var prdIdParameter = prdId.HasValue ?
                new ObjectParameter("PrdId", prdId) :
                new ObjectParameter("PrdId", typeof(int));
    
            var prdCodeParameter = prdCode != null ?
                new ObjectParameter("PrdCode", prdCode) :
                new ObjectParameter("PrdCode", typeof(string));
    
            var prdDescParameter = prdDesc != null ?
                new ObjectParameter("PrdDesc", prdDesc) :
                new ObjectParameter("PrdDesc", typeof(string));
    
            var prdPriceParameter = prdPrice.HasValue ?
                new ObjectParameter("PrdPrice", prdPrice) :
                new ObjectParameter("PrdPrice", typeof(decimal));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("Active", active) :
                new ObjectParameter("Active", typeof(int));
    
            var cMByParameter = cMBy != null ?
                new ObjectParameter("CMBy", cMBy) :
                new ObjectParameter("CMBy", typeof(string));
    
            var cMDateParameter = cMDate.HasValue ?
                new ObjectParameter("CMDate", cMDate) :
                new ObjectParameter("CMDate", typeof(System.DateTime));
    
            var deleteParameter = delete.HasValue ?
                new ObjectParameter("Delete", delete) :
                new ObjectParameter("Delete", typeof(int));
    
            var catIdParameter = catId.HasValue ?
                new ObjectParameter("CatId", catId) :
                new ObjectParameter("CatId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_I_tblProducts", prdIdParameter, prdCodeParameter, prdDescParameter, prdPriceParameter, activeParameter, cMByParameter, cMDateParameter, deleteParameter, catIdParameter);
        }
    
        public virtual ObjectResult<vw_tblProducts> spGetProductList(Nullable<int> prdId)
        {
            var prdIdParameter = prdId.HasValue ?
                new ObjectParameter("PrdId", prdId) :
                new ObjectParameter("PrdId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_tblProducts>("spGetProductList", prdIdParameter);
        }
        public virtual ObjectResult<vw_tblCategory> spGetCategoryList(Nullable<int> catId)
        {
            var catIdParameter = catId.HasValue ?
                new ObjectParameter("CatId", catId) :
                new ObjectParameter("CatId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<vw_tblCategory>("spGetCategoryList", catIdParameter);
        }
    }
}
