//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;

namespace AuthModule
{
    public class CredtAppDdwn
    {
        public int Id { get; set; }
        public string CreditAppDesc { get; set; }
        public bool? Active { get; set; }
    }
}