//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;

namespace AuthModule
{
    public class tblOrder
    {
        public Guid OrderId { get; set; }
        public int CustId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime OrderCreatedDate { get; set; }
        public string DeliveryZip { get; set; }
        public int PrdId { get; set; }
        public int Qty { get; set; }           
        public DateTime ItemsCreatedDate { get; set; }
        public string OrderBy { get; set; }
       
    }
}