//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int PrdId { get; set; }
        public string PrdCode { get; set; }
        public string PrdDesc { get; set; }
        public decimal PrdPrice { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public int CatId { get; set; }
    }
}
