//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeviceRegistration
    {
        public string UserID { get; set; }
        public string DeviceID { get; set; }
        public int AppID { get; set; }
        public string Email { get; set; }
        public string DeviceName { get; set; }
        public bool DeviceConfirmed { get; set; }
        public string DeviceOs { get; set; }
        public string DeviceOsVersion { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
