
Create     view [dbo].[vwTrps] as
SELECT [trpID]
      ,[trpRsrvtnID]
      ,[trpPckDate]
      ,[trpPckTm]
      ,[trpPssngrs]
      ,[trpCst]
      ,[trpPckLctnTpe]
      ,[trpPckLctnUnqID]
      ,[trpPckLctnSubUnqID]
      ,[trpPckLctnTm]
      ,[trpDrpLctnTpe]
      ,[trpDrpLctnUnqID]
      ,[trpDrpLctnSubUnqID]
      ,[trpDrpLctnTm]
      ,[trpWC]
      ,[trpWCfld]
      ,[trpAddtnfo]
      ,[trpCrtdDtTm]
      ,[trpCrtdBy]
      ,[trpUpdt]
      ,[trpUpdtBy]
  FROM [dbo].[tblTrps]
